### PR TITLE
Enables setup for updating/invalidating articles cache from Facebook scraper

### LINKED ISSUE #878: IA version of post doesn't update after being resaved
## Steps required to reproduce the problem

(UPDATED: Previously I described the old procedure where posts were automatically sent to FB at publish time, because there was no announcement that this had been removed)

1. Publish a post and share it to facebook so IA is published and shows up in Page Manager etc.
2. Edit the post and change content
3. Re-save the post and check the IA version

## Expected Result

Previously, this worked as it should, and the post's IA version would be updated and you'd see the new content in Page Manager and in the Facebook mobile app. 

You could also see it had been updated in the "Production Articles" section of "Publishing Tools" in the FB page admin.

This meant that critical updates and corrections to articles would be reflected in the IA version, and Facebook users saw the truth.

## Actual Result 

IA version of the post is never updated. In Page Manager/FB mobile app the content never updates. 

Additionally, in "Production Articles" section of "Publishing Tools" I can see that the **Last Updated** time never updates. 

Needless to say this is **wildly horrifying** as a publisher. Our authors update posts with the expectation that their updates will be seen by all visitors, and in this case very likely **most** of our visitors will see the uncorrected IA version. 

Please confirm that this is a problem specific to us, because if it effects all users it is a disaster. 

@see [WP Forum Thread from Dec 2017 where a user has this same problem of IA not updating](https://wordpress.org/support/topic/update-facebook-instant-article-with-new-content/)

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 4.0.6
* WordPress version: 4.9.4
* PHP version: 7.0.23

### PR DESCRIPTION
**Pull request by everton-rosario**
This PR:

* [x] Creates a configuration settings where you can inform `App ID`, `App secret` and `Access Token`
* [x] Calls re-scrape with the App settings if well set
* [x] Treats errors on configuration and properly shows error message if not successful rescraped

Fixes #878

### CODE REVIEW

**Comment by jerclarke** [comment]
I'm having a problem running composer install on this branch of the plugin, here's my output: 

```
$ git branch -v
* fix/auto-update 7e27c79 Fixed issue with null parameter call
  master          c616ef1 Merge pull request #896 from playbuzz/feature/support-playbuzz-plugin-future-version

$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 1 install, 0 updates, 0 removals

                                                                                                                                                                                                
  [RuntimeException]                                                                                                                                                                            
  /Users/ungratefulbiped/Sites/facebook-instant-articles-git-dev-setup/facebook-instant-articles-wp/vendor/facebook/facebook-instant-articles-sdk-php does not exist and could not be created.                                                                                                                                                                                                  
```

What can  I do to overcome this? Without being able to run `composer install` on the `fix/auto-update` branch, I get this error on my WP site when I try to save a post:

> Fatal error: Class 'Facebook\InstantArticles\Transformer\Transformer' not found in /[...]/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php on line 612

In this case the other obvious bug is that the FB IA metabox never finishes loading in the editor, the spinner just spins forever, presumably because the AJAX failed with the same Fatal error.

**Comment by everton-rosario** [comment]
@jerclarke Looks like the composer process was unable to find the package hosted in packagist: https://packagist.org/packages/facebook/facebook-instant-articles-sdk-php

The Fatal error you pointed out is a class contained by that package not downloaded.

I'll take a look and get back to you.

**Comment by jerclarke** [comment]
Thanks @everton-rosario It's my first time so if you are able to get it all working on your end, starting from a fresh baseline, then I'm willing to go back in and try to figure each thing out. Just want to make sure that a fresh setup DOES work for others before putting that time in, I'm completely new to composer unfortunately.

**Comment by everton-rosario** [comment]
I couldn't reproduce exactly the same issue with composer, but digging a little more about it, and after a `composer update` I got something like your issue (but still, can be unrelated).

```
  [Composer\Downloader\TransportException]                                                                           
  The "http://packagist.org/p/provider-2018-01%24ca919959183371fce338c9f5d011ff72ccba4104f04a3e791852d659a0caaf08.j  
  son" file could not be downloaded (HTTP/1.1 404 Not Found)                                                         
```

I've  used this time to also update the minimal version of the SDK to 1.9.0 and updated the `composer.json` version into this PR.
This should be enough for you to invalidate your local composer cache:

```
composer clear 
composer update
composer install
```

**Comment by jerclarke** [comment]
Sorry @everton-rosario I'm still having the same problem, and I think I tried everything:

* updated git (`git pull`) on both directories (*-sdk-php/ and *-wp/)
* ran full `composer clear|update|install` routine on *-sdk-php/
* ran `composer clear` on *-wp (no errors)

Result

* running `composer update` (or install) causes this error:

> [RuntimeException]                                                                                                                                            
>  /Users/[...]/Sites/facebook-instant-articles-git-dev-setup/facebook-instant-articles-wp/vendor/facebook/facebook-instant-articles-sdk-php does not  exist and could not be created.      

```BASH
laptop:facebook-instant-articles-sdk-php $ git pull
Already up-to-date.
laptop:facebook-instant-articles-sdk-php $ composer clear
Cache directory does not exist (cache-vcs-dir): 
Clearing cache (cache-repo-dir): /Users//.composer/cache/repo
Clearing cache (cache-files-dir): /Users//.composer/cache/files
Clearing cache (cache-dir): /Users//.composer/cache
All caches cleared.
laptop:facebook-instant-articles-sdk-php $ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
laptop:facebook-instant-articles-sdk-php $ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

laptop:facebook-instant-articles-sdk-php $ cd ../facebook-instant-articles-wp/
laptop:facebook-instant-articles-wp $ gitp
Already up-to-date.
laptop:facebook-instant-articles-wp $ composer clear
Cache directory does not exist (cache-vcs-dir): 
Clearing cache (cache-repo-dir): /Users//.composer/cache/repo
Clearing cache (cache-files-dir): /Users//.composer/cache/files
Clearing cache (cache-dir): /Users//.composer/cache
All caches cleared.
laptop:facebook-instant-articles-wp $ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals

                                                                                                                                                                
  [RuntimeException]                                                                                                                                            
  /Users//Sites/facebook-instant-articles-git-dev-setup/facebook-instant-articles-wp/vendor/facebook/facebook-instant-articles-sdk-php does not  
   exist and could not be created.                                                                                                                              
                                                                                                                                                                

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

laptop:facebook-instant-articles-wp $ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 1 install, 0 updates, 0 removals

                                                                                                                                                                
  [RuntimeException]                                                                                                                                            
  /Users//Sites/facebook-instant-articles-git-dev-setup/facebook-instant-articles-wp/vendor/facebook/facebook-instant-articles-sdk-php does not  
   exist and could not be created.                                                                                                                              
                                                                                                                                                                

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

laptop:facebook-instant-articles-wp $ composer update
```

**Comment by jerclarke** [comment]
Okay, I take that back. I tried again, from the start, and now it works as expected. Probably anyone who tried a fresh setup in the last little while will have to do the same. 

Please make sure to update those dependencies and test a fresh install when they change.

**Pull request merged**
