### PR TITLE
Add an option to set a footer

### LINKED ISSUE #261: Additional setting option to apply a global footer
This feature request is to add an additional option in the settings to set a footer which would apply to all articles.

Example use case: Useful for copyright information.

Reference:
https://wordpress.org/support/topic/footer-110?replies=1
https://wordpress.org/support/topic/footer-customization-4/
https://wordpress.org/support/topic/customizing-footer-5/

### PR DESCRIPTION
**Pull request by sakatam**
fixes #261

- [x] Set footer element during the construction of IA document
- [x] Rename "Style" setting to "Appearance"
- [x] Consolidate appearance settings logic into one function

image

image

### CODE REVIEW

**Comment by diegoquinteiro** [comment]
There was an idea from @demoive and @everton-rosario to change the taxonomy and remove the high level "Footer" section.

I personally like the way @sakatam did it here for the simplicity and because it allows a nice future expansion to include other footer elements and options there (setting up Credits for instance).

Please @everton-rosario and @demoive add your reasoning to this thread so it is documented.

I'll approve the diff as it is and defer to @sakatam for the final decision on changing the taxonomy or not.

**Comment by demoive** [comment]
Right, so from the requests I've seen, the reason to have the option for a global footer setting is to make it easy for setting the content of the footer globally. In this sense, I classify it as a setting for the "theme" of an article (or "template") which lends itself for being under the "Styles" section.

@everton-rosario made a point that if this were the case, perhaps "Styles" could be renamed to something else more encompassing, for example: 

- Appearance
- Template
- Styling
- IA markup setup
- Markup settings

**Comment by demoive** [comment]
To @diegoquinteiro's point, however, in the future, I could also foresee the desire to define multiple footers, each to be applied to articles based on some condition — such as based on a category or tag. In this case, it could make sense to have a dedicated section for these settings, i.e. keep things as they are.

**Comment by demoive** [comment]
Either way, I think this implementation is spot on. Great job here.

**Comment by sakatam** [comment]
Thank you guys all for your suggestions! I agree with moving the copyright setting into the "Style" section and renaming the section to more encompassing one. Once we will need to expand the footer setting in the future, we can split it and have a dedicated section.

**Comment by sakatam** [comment]
Pushed the new version. Now the copyright setting is in the new "Appearance" section which includes Style and RTL settings.

**Comment by sakatam** [comment]
@diegoquinteiro @demoive @everton-rosario Do you guys have any remaining concerns on this change?

**Comment by diegoquinteiro** [comment]
Looks great. Merging. =)

**Comment by samichamoun** [comment]
Just updated to the latest version of the plugin and don't see this option??

**Comment by sakatam** [comment]
@samichamoun Unfortunately, this one is not in v3.3. Will definitely be included in the next release!

**Comment by samichamoun** [comment]
Ah, no worries. I notice that the screenshot says no tags can be added. Is there a reason why we can't put any hyperlinks in here as I've seen a number of pages using the footer for this?

**Comment by rondavilar** [comment]
I've been inserting footers manually in every article which is tedious, plus they get replaced every time the article updates. Is there a way to do this at the PHP level with hyperlink tags? Completely new to programming.

**Comment by sakatam** [comment]
@samichamoun 

> Is there a reason why we can't put any hyperlinks in here as I've seen a number of pages using the footer for this?

This is simply due to [the restriction of the SDK](https://github.com/facebook/facebook-instant-articles-sdk-php/blob/master/src/Facebook/InstantArticles/Elements/Footer.php#L105-L111) that this plugin depends on. However, since our platform allows hyperlinks in here, we should be able to do that within this plugin, too. I will file an issue for this. Thank you for pointing this out!

**Comment by sakatam** [comment]
Filed an issue for rich formats: #619

**Pull request merged**
