### PR TITLE
Adds caching to instant_articles_embed_oembed_html

### LINKED ISSUE #685: Global wordpress performances and oEmbeds
I was investigating a performance issues on my websites (two medium audiences), and it seems that the plugin waste of lot of ressources and uselessly break the wordpress oembed discover cache in a way I don't yet understand.

## The problem

We use a log of self embeds (using a block to promote our own article on another article) and our /feed is not in the cache (30 posts).

So for each user asking for /feed and for each post containing a embed, it generate one "local" request in order to discover the oembed iframe URL. A lot of "internal" http requests for just one client.

Wordpress seems to usually have a cache for oembed, but the code in facebook-instant-articles/embeds.php to not use that cache for my /feed.

## First investigation / The place where it happens?

The function `instant_articles_embed_oembed_html` make use of  `wp_oembed->get_provider` which use `discover` which make external request to call the embeded URL in order to find the embed iframe URL. A parameter exists to force non-discovery, but is not used.

The embeds.php file is actually included on all the request, `remove_all_filters( 'embed_oembed_html' );` is then run on each requests and not only instant articles endpoint, potentially breaking other things.

Same for `add_filter( 'embed_oembed_html', 'instant_articles_embed_oembed_html', 10, 4 );`

---

**Version Info**

* Plugin version: 3.3.3
* WordPress version: 4.7.5
* PHP version: PHP 5.6.30-0+deb8u1

### PR DESCRIPTION
**Pull request by emrikol**
For each oEmbed on a page, an uncached remote request is made to check the oEmbed provider's URL.  This patch adds a level of caching to stop from having to check each oEmbed on every page load.

It's unlikely that an oEmbed provider will change for a specific URL, so there shouldn't be any need to specify an expiration on the good cached data.

This PR:

* [x] Adds caching to instant_articles_embed_oembed_html

Fixes #685

### CODE REVIEW

**Comment by emrikol** [comment]
Looks related to #337 too

**Comment by timjacobi** [comment]
LGTM, thanks for your contribution!

**Comment by sboisvert** [comment]
Hi @timjacobi I was just wondering when the next version (that included this fix) was planned for (to see if I should patch our current versions or wait for a new version) Thanks!

**Comment by timjacobi** [comment]
We currently don’t have a release date so I recommend to patch for now.

**Pull request merged**
