### PR TITLE
Show message on meta-box when post is filtered out

### PR DESCRIPTION
**Pull request by diegoquinteiro**
This PR:

* [x] Adds a message on the meta-box for when the post was filtered out programatically.

Follows #504

### CODE REVIEW

**Comment by everton-rosario** [comment]
@philipjohn please add this to the next release.

**Comment by msurguy** [comment]
I just installed this plugin and am seeing message "This post will not be submitted to Instant Articles due to a rule created in your site" on all new posts. Upon reviewing the code for this PR it appears that `$shoud_publish_post` is not defined anywhere, thus triggering the message to show. 

Is that a fair assumption that the variable `$should_submit_post` should be used instead of `$shoud_publish_post` instead ?

**Comment by apollosk** [comment]
I'm seeing the same message on all new posts after I updated the plugin to v. 3.2.1. Previously everything worked great. I'm certain that my custom rules are OK.

`{
"rules":
[{
"class": "IgnoreRule",
"selector": "div.td-gallery-slide-top"
},
{
"class": "IgnoreRule",
"selector": "style"
},
{
"class": "IgnoreRule",
"selector": "div.td-button"
},
{
"class": "PassThroughRule",
"selector": "div.td-doubleSlider-1"
},
{
"class": "PassThroughRule",
"selector": "div.td-slide-on-2-columns"
},
{
"class": "PassThroughRule",
"selector": "div.td-doubleSlider-2"
},
{
"class": "PassThroughRule",
"selector": "div.td-slider"
},
{
"class": "PassThroughRule",
"selector": "div.td-slide-item"
},
{
"class": "SlideshowRule",
"selector" : "div.post_td_gallery"
},
{
"class": "SlideshowImageRule",
"selector" : "div.td-slide-item",
"properties" : {
"image.url" : {
"type" : "string",
"selector" : "a.slide-gallery-image-link",
"attribute": "href"
},
"caption.title" : {
"type" : "string",
"selector" : "div.td-gallery-slide-copywrite"
}
}
},
    {
        "class": "ImageRule",
        "selector": "//img|//p[img]|//p[a[img]]|//a[img]",
        "properties": {
            "image.url": {
                "type": "string",
                "selector": "img",
                "attribute": "src"
            },
            "image.caption": {
                "type": "element",
                "selector": "img[@alt]"
            },
            "image.like" : {
                "type" : "exists",
                "selector" : "img"
            },
            "image.comments" : {
                "type" : "exists",
                "selector" : "img"
            }
        }
    }
]
}`

**Comment by diegoquinteiro** [comment]
Thanks for reporting; this was a typo that unfortunately went through the release. I'm going to fix and release on 3.2.2 within the day.

Thank you!

**Comment by diegoquinteiro** [comment]
That said, only the message is affected, meaning your articles are being submitted to IA regardless.

**Comment by apollosk** [comment]
@diegoquinteiro Exactly. Instant Articles are still being submitted to FB.

**Pull request merged**
