### PR TITLE
Refactor to use transform string

### LINKED ISSUE #339: Japanese post title is corrupted. $title needs to be helped by mb_convert_encoding() as with $content in Instant_Articles_Post::to_instant_article()
Post content is converted by `$content = mb_convert_encoding( $content, 'HTML-ENTITIES', get_option( 'blog_charset' ) )` before DOMDocument in class-instant-articles-publisher.php, but post title is not converted. So Japanese post title is corrupted.

---

** Version Info **

* WordPress version: WordPress.com VIP

### PR DESCRIPTION
**Pull request by yssk22**
This PR:

* [x] improve encoding handling by IA the SDK function `transformString` and remove the complexities of `loadHTML` things.

Follows #395

Relates to #369, #344

Fixes #339

### CODE REVIEW

**Comment by everton-rosario** [comment]
LGTM
:shipit: 

@philipjohn please include this fix on the next patch regarding the version of SDK.

**Comment by LiviuJianu** [comment]
Any chance this gets in the 3.2 milestone?

**Comment by demoive** [comment]
@philipjohn I didn't intend to merge this myself. I simply wanted to resolve the merge conflict, but since it was originally committed straight into master, this was the result. Hope this is ok!

**Comment by kawarano** [comment]
Thanks @yssk22 san

@philipjohn some of the merged changes of this PR were reverted with 49c22d0 commit. Could you please re-merge it? It prevents `$title` which contains multibyte characters from being garbled.

**Comment by sakatam** [comment]
@yssk22 thank you for figuring out! I created a quick PR for this and it'll hopefully be included in the next release.

**Pull request merged**
