### PR TITLE
Article with password protection

### LINKED ISSUE #405: Don't process if this post is password protected
# Steps required to reproduce the problem

1.  Publish password protected post
2.  Check instant article feed on facebook

# Expected Result

* excluded password protected post

# Actual Result

* included password protected post

---

** Version Info **

* Plugin version: 3.0.1
* WordPress version:  4.5.3
* PHP version: 7.0.8

### PR DESCRIPTION
**Pull request by everton-rosario**
This PR:

* [x] Removes Instant Article if it just started to be password protected
* [x] Prevents to submit it again while password protected

Fixes #405

### CODE REVIEW

**Comment by everton-rosario** [comment]
@philipjohn Can you check this and include in the release 3.1.1?

**Comment by philipjohn** [comment]
@everton-rosario Could you take a look at the test failures here? I wonder if the tests themselves need to account for password-protected posts?

**Comment by philipjohn** [comment]
Nevermind, I think they're generally broken rather than failing.

**Comment by everton-rosario** [comment]
@philipjohn Yes, there is a PR that fixed the broken tests.

**Pull request merged**
