### PR TITLE
Check for undefined index

### LINKED ISSUE #404: PHP error in Custom transformer rules textarea
# Steps required to reproduce the problem

Seeing this error in the textarea when enabling Custom transformer rules:

Notice: Undefined index: double_encode in /var/app/current/wp-content/plugins/fb-instant-
articles/settings/class-instant-articles-option.php on line 386

---

** Version Info **

* Plugin version: 3.0.1
* WordPress version: 4.5.3
* PHP version: 5.6

### PR DESCRIPTION
**Pull request by gemedet**
This PR checks if the `double_encode` key exists before using it.

Fixes #404

### CODE REVIEW

**Comment by everton-rosario** [comment]
@gemedet thanks for your PR. Can you rebase it?

**Comment by everton-rosario** [comment]
LGTM, can be merged as @gemedet rebases it.

**Comment by gemedet** [comment]
@everton-rosario Updated!

**Comment by everton-rosario** [comment]
@philipjohn waiting for you to merge it.

**Comment by philipjohn** [comment]
Thanks @gemedet !

**Pull request merged**
